ALTER TABLE concept_questions
  ADD COLUMN IF NOT EXISTS bloom_level TEXT,
  ADD COLUMN IF NOT EXISTS hots BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS topic TEXT,
  ADD COLUMN IF NOT EXISTS source TEXT DEFAULT 'AI Textbook Upload';
