import { getSupabaseAdmin } from '../services/supabase';
import { logger } from '../utils/logger';

interface CurriculumItem {
  grade: string;
  subject: string;
  chapter: string;
  topic: string;
  concept: string;
  learning_objective: string;
}

const curriculumData: CurriculumItem[] = [
  // === GRADE 6 MATHEMATICS ===
  {
    grade: '6',
    subject: 'Mathematics',
    chapter: 'Chapter 1: Knowing Our Numbers',
    topic: 'Number System and Place Value',
    concept: 'Large Numbers and Estimation',
    learning_objective: 'Understand place value in Indian and International systems, compare numbers, and round off numbers to nearest tens, hundreds, and thousands.',
  },
  {
    grade: '6',
    subject: 'Mathematics',
    chapter: 'Chapter 2: Whole Numbers',
    topic: 'Whole Numbers properties',
    concept: 'Number Line and Properties',
    learning_objective: 'Understand natural numbers, whole numbers, represent them on a number line, and apply closure, commutative, associative, and distributive properties.',
  },
  {
    grade: '6',
    subject: 'Mathematics',
    chapter: 'Chapter 3: Playing with Numbers',
    topic: 'Factors and Multiples',
    concept: 'Prime Factorisation, HCF and LCM',
    learning_objective: 'Identify factors and multiples, classify prime and composite numbers, find HCF and LCM, and understand divisibility rules.',
  },
  {
    grade: '6',
    subject: 'Mathematics',
    chapter: 'Chapter 4: Basic Geometrical Ideas',
    topic: 'Elementary Geometry',
    concept: 'Points, Lines, Angles and Polygons',
    learning_objective: 'Differentiate between point, line segment, ray, intersecting and parallel lines, and identify angles, triangles, and quadrilaterals.',
  },
  {
    grade: '6',
    subject: 'Mathematics',
    chapter: 'Chapter 5: Understanding Elementary Shapes',
    topic: 'Geometrical Shapes measurement',
    concept: 'Angles, Triangles classification, 3D Shapes',
    learning_objective: 'Measure line segments and angles, classify triangles based on sides and angles, identify quadrilaterals, and name basic 3D shapes.',
  },
  {
    grade: '6',
    subject: 'Mathematics',
    chapter: 'Chapter 6: Integers',
    topic: 'Integers representation',
    concept: 'Negative numbers and Number Line operations',
    learning_objective: 'Understand negative numbers, represent integers on a number line, compare them, and perform basic addition and subtraction.',
  },
  {
    grade: '6',
    subject: 'Mathematics',
    chapter: 'Chapter 7: Fractions',
    topic: 'Fractions operations',
    concept: 'Proper, Improper, Equivalent Fractions',
    learning_objective: 'Represent fractions on a number line, classify proper, improper, mixed, and equivalent fractions, and perform addition and subtraction.',
  },
  {
    grade: '6',
    subject: 'Mathematics',
    chapter: 'Chapter 8: Decimals',
    topic: 'Decimals comparison',
    concept: 'Decimals on Number Line and Money/Weight conversion',
    learning_objective: 'Understand decimals as parts of tenths and hundredths, represent them on a number line, compare, and convert units of money, length, and weight.',
  },
  {
    grade: '6',
    subject: 'Mathematics',
    chapter: 'Chapter 9: Data Handling',
    topic: 'Introduction to Data',
    concept: 'Recording Data, Pictographs and Bar Graphs',
    learning_objective: 'Collect and organize data, draw and interpret pictographs and bar graphs using appropriate scales.',
  },
  {
    grade: '6',
    subject: 'Mathematics',
    chapter: 'Chapter 10: Mensuration',
    topic: 'Perimeter and Area',
    concept: 'Formulae for Rectangles and Squares',
    learning_objective: 'Calculate the perimeter of polygons, and compute the area of squares and rectangles.',
  },
  {
    grade: '6',
    subject: 'Mathematics',
    chapter: 'Chapter 11: Algebra',
    topic: 'Introduction to Algebra',
    concept: 'Variables, Expressions and simple Equations',
    learning_objective: 'Understand the concept of variables, write basic algebraic expressions, and identify simple equations.',
  },
  {
    grade: '6',
    subject: 'Mathematics',
    chapter: 'Chapter 12: Ratio and Proportion',
    topic: 'Ratios comparison',
    concept: 'Proportion and Unitary Method',
    learning_objective: 'Compute ratios, check if terms are in proportion, and solve practical word problems using the unitary method.',
  },

  // === GRADE 6 SCIENCE ===
  {
    grade: '6',
    subject: 'Science',
    chapter: 'Chapter 1: Food: Where Does It Come From?',
    topic: 'Food Variety and Sources',
    concept: 'Ingredients, Herbivores, Carnivores, Omnivores',
    learning_objective: 'Identify components of different food items and trace their origins to plants or animals.',
  },
  {
    grade: '6',
    subject: 'Science',
    chapter: 'Chapter 2: Components of Food',
    topic: 'Nutrients in Food',
    concept: 'Carbohydrates, Proteins, Fats, Balanced Diet, Deficiency Diseases',
    learning_objective: 'Test for presence of starch, protein, and fat, plan a balanced diet, and list diseases caused by nutrient deficiencies.',
  },
  {
    grade: '6',
    subject: 'Science',
    chapter: 'Chapter 3: Fibre to Fabric',
    topic: 'Textile Materials',
    concept: 'Natural vs Synthetic Fibres, Spinning, Weaving',
    learning_objective: 'Trace the journey of cotton and jute from plant to yarn and fabric, and differentiate natural from synthetic fibres.',
  },
  {
    grade: '6',
    subject: 'Science',
    chapter: 'Chapter 4: Sorting Materials into Groups',
    topic: 'Properties of Materials',
    concept: 'Lustre, Hardness, Solubility, Transparency',
    learning_objective: 'Group objects based on properties such as appearance, solubility in water, transparency, and density.',
  },
  {
    grade: '6',
    subject: 'Science',
    chapter: 'Chapter 5: Separation of Substances',
    topic: 'Separation methods',
    concept: 'Handpicking, Winnowing, Filtration, Decantation, Evaporation',
    learning_objective: 'Choose appropriate separation techniques to isolate components of a mixture based on physical properties.',
  },
  {
    grade: '6',
    subject: 'Science',
    chapter: 'Chapter 6: Changes Around Us',
    topic: 'Classification of Changes',
    concept: 'Reversible and Irreversible Changes',
    learning_objective: 'Distinguish between changes that can be reversed (like melting) and those that cannot (like burning).',
  },
  {
    grade: '6',
    subject: 'Science',
    chapter: 'Chapter 7: Getting to Know Plants',
    topic: 'Plant Morphology',
    concept: 'Herbs, Shrubs, Trees, Stem, Root, Leaf, Flower parts',
    learning_objective: 'Identify types of plants, describe functions of stem and roots, explain photosynthesis in leaves, and dissect flower parts.',
  },
  {
    grade: '6',
    subject: 'Science',
    chapter: 'Chapter 8: Body Movements',
    topic: 'Locomotion and Skeleton',
    concept: 'Bones, Joints (Ball & Socket, Hinge), Gait of Animals',
    learning_objective: 'Identify joints in the human skeleton and compare movement mechanisms in humans, earthworms, snails, and fish.',
  },
  {
    grade: '6',
    subject: 'Science',
    chapter: 'Chapter 9: The Living Organisms and Their Surroundings',
    topic: 'Habitats and Adaptations',
    concept: 'Terrestrial/Aquatic Habitats, Biotic/Abiotic Factors, Adaptations',
    learning_objective: 'Analyze how structural adaptations help organisms survive in deserts, mountains, and oceans.',
  },
  {
    grade: '6',
    subject: 'Science',
    chapter: 'Chapter 10: Motion and Measurement of Distances',
    topic: 'Measurement and Kinematics',
    concept: 'Standard Units (SI), Rectilinear, Circular, Periodic Motion',
    learning_objective: 'Measure length accurately using standard SI units and classify types of motion with examples.',
  },
  {
    grade: '6',
    subject: 'Science',
    chapter: 'Chapter 11: Light, Shadows and Reflections',
    topic: 'Optics basics',
    concept: 'Opaque, Transparent, Translucent, Shadows, Mirror Reflection',
    learning_objective: 'Explain the rectilinear propagation of light, construct a pinhole camera, and explain shadow and image formation.',
  },
  {
    grade: '6',
    subject: 'Science',
    chapter: 'Chapter 12: Electricity and Circuits',
    topic: 'Electrical Systems',
    concept: 'Electric Cell, Bulb, Switch, Conductors and Insulators',
    learning_objective: 'Assemble a simple working electric circuit and categorize materials as conductors or insulators.',
  },
  {
    grade: '6',
    subject: 'Science',
    chapter: 'Chapter 13: Fun with Magnets',
    topic: 'Magnetism',
    concept: 'Magnetic Poles, Attraction/Repulsion, Magnetic Compass',
    learning_objective: 'Identify magnetic substances, locate poles of a magnet, and construct a simple magnetic compass for direction finding.',
  },
  {
    grade: '6',
    subject: 'Science',
    chapter: 'Chapter 14: Water',
    topic: 'Water Cycle',
    concept: 'Evaporation, Condensation, Water depletion, Rainwater Harvesting',
    learning_objective: 'Describe the steps of the water cycle and evaluate conservation techniques like rainwater harvesting.',
  },
  {
    grade: '6',
    subject: 'Science',
    chapter: 'Chapter 15: Air Around Us',
    topic: 'Atmospheric Air',
    concept: 'Composition of Air (Oxygen, Nitrogen, CO2), Respiration support',
    learning_objective: 'Understand composition of air, prove oxygen supports burning, and explain how plants and animals exchange gases.',
  },

  // === GRADE 7 MATHEMATICS ===
  {
    grade: '7',
    subject: 'Mathematics',
    chapter: 'Chapter 1: Integers',
    topic: 'Operations on Integers',
    concept: 'Properties of Multiplication and Division of Integers',
    learning_objective: 'Perform arithmetic operations on integers and apply commutative, associative, and distributive properties to simplify calculations.',
  },
  {
    grade: '7',
    subject: 'Mathematics',
    chapter: 'Chapter 2: Fractions and Decimals',
    topic: 'Rational Operations',
    concept: 'Multiplication/Division of Fractions and Decimals',
    learning_objective: 'Multiply and divide fractions by whole numbers/fractions, multiply and divide decimal numbers, and solve word problems.',
  },
  {
    grade: '7',
    subject: 'Mathematics',
    chapter: 'Chapter 3: Data Handling',
    topic: 'Central Tendency and Representation',
    concept: 'Mean, Median, Mode, Double Bar Graphs, Probability',
    learning_objective: 'Calculate mean, median, and mode, construct and interpret double bar graphs, and calculate simple probability.',
  },
  {
    grade: '7',
    subject: 'Mathematics',
    chapter: 'Chapter 4: Simple Equations',
    topic: 'Linear Equations basics',
    concept: 'Setting up and Solving simple Linear Equations',
    learning_objective: 'Formulate equations from word statements, solve linear equations using transposition, and apply to real-world scenarios.',
  },
  {
    grade: '7',
    subject: 'Mathematics',
    chapter: 'Chapter 5: Lines and Angles',
    topic: 'Geometry of Angles',
    concept: 'Supplementary/Complementary Angles, Transversal lines',
    learning_objective: 'Identify adjacent, linear pair, vertically opposite, complementary, and supplementary angles, and verify parallel lines properties.',
  },
  {
    grade: '7',
    subject: 'Mathematics',
    chapter: 'Chapter 6: The Triangle and its Properties',
    topic: 'Properties of Triangles',
    concept: 'Altitude, Exterior Angles, Pythagoras Theorem',
    learning_objective: 'Understand medians and altitudes, apply exterior angle property and angle sum property, and apply the Pythagoras theorem.',
  },
  {
    grade: '7',
    subject: 'Mathematics',
    chapter: 'Chapter 7: Congruence of Triangles',
    topic: 'Congruency criteria',
    concept: 'SSS, SAS, ASA, RHS Congruence criteria',
    learning_objective: 'Explain the concept of congruence and apply SSS, SAS, ASA, and RHS criteria to prove triangle congruence.',
  },
  {
    grade: '7',
    subject: 'Mathematics',
    chapter: 'Chapter 8: Comparing Quantities',
    topic: 'Percentages and Financial Math',
    concept: 'Ratios, Percentage increase/decrease, Profit & Loss, SI',
    learning_objective: 'Convert ratios to percentages, calculate profit/loss percent, and compute simple interest using the formula.',
  },
  {
    grade: '7',
    subject: 'Mathematics',
    chapter: 'Chapter 9: Rational Numbers',
    topic: 'Rational Number Operations',
    concept: 'Comparison, Number Line representation, Arithmetic',
    learning_objective: 'Define rational numbers, represent them on a number line, compare them, and perform arithmetic operations.',
  },
  {
    grade: '7',
    subject: 'Mathematics',
    chapter: 'Chapter 10: Practical Geometry',
    topic: 'Construction',
    concept: 'Constructing parallel lines and Triangles',
    learning_objective: 'Construct a line parallel to a given line, and construct triangles using SSS, SAS, ASA, and RHS parameters.',
  },
  {
    grade: '7',
    subject: 'Mathematics',
    chapter: 'Chapter 11: Perimeter and Area',
    topic: 'Mensuration',
    concept: 'Area of Parallelogram, Triangle, Circle, path area',
    learning_objective: 'Derive and apply formulas for area of parallelograms, triangles, and circles, and find area of paths or borders.',
  },
  {
    grade: '7',
    subject: 'Mathematics',
    chapter: 'Chapter 12: Algebraic Expressions',
    topic: 'Algebraic Operations',
    concept: 'Terms, Coefficients, Addition/Subtraction of Expressions',
    learning_objective: 'Identify terms, factors, and coefficients, and add and subtract algebraic expressions containing like terms.',
  },
  {
    grade: '7',
    subject: 'Mathematics',
    chapter: 'Chapter 13: Exponents and Powers',
    topic: 'Exponents laws',
    concept: 'Laws of Exponents, Scientific notation',
    learning_objective: 'Apply laws of exponents to simplify expressions, and express large numbers in scientific (standard) notation.',
  },

  // === GRADE 7 SCIENCE ===
  {
    grade: '7',
    subject: 'Science',
    chapter: 'Chapter 1: Nutrition in Plants',
    topic: 'Plant Nutrition',
    concept: 'Photosynthesis, Autotrophs, Saprotrophs, Symbiosis',
    learning_objective: 'Describe the process of photosynthesis, understand insectivorous plants, and explain nutrient replenishment in soil.',
  },
  {
    grade: '7',
    subject: 'Science',
    chapter: 'Chapter 2: Nutrition in Animals',
    topic: 'Animal Nutrition',
    concept: 'Human Digestive System, Digestion in Grass Cutters, Amoeba feeding',
    learning_objective: 'Trace the path of food through the human alimentary canal, describe functions of organs, and understand digestion in ruminants.',
  },
  {
    grade: '7',
    subject: 'Science',
    chapter: 'Chapter 3: Fibre to Fabric',
    topic: 'Animal Fibres',
    concept: 'Processing Wool, Life Cycle of Silk Moth, Sericulture',
    learning_objective: 'Explain the life cycle of the silkworm, describe shearing, scouring, sorting of wool, and detail silk extraction.',
  },
  {
    grade: '7',
    subject: 'Science',
    chapter: 'Chapter 4: Heat',
    topic: 'Thermal Physics',
    concept: 'Conduction, Convection, Radiation, Thermometers',
    learning_objective: 'Measure temperature using clinical and laboratory thermometers, and analyze heat transfer mechanisms with real-world examples.',
  },
  {
    grade: '7',
    subject: 'Science',
    chapter: 'Chapter 5: Acids, Bases and Salts',
    topic: 'Chemistry basics',
    concept: 'Indicators, Neutralisation in everyday life',
    learning_objective: 'Identify acidic and basic substances using natural indicators (litmus, turmeric) and describe neutralisation reactions.',
  },
  {
    grade: '7',
    subject: 'Science',
    chapter: 'Chapter 6: Physical and Chemical Changes',
    topic: 'Chemical Reactions introduction',
    concept: 'Rusting of Iron, Galvanisation, Crystallisation',
    learning_objective: 'Differentiate between physical and chemical changes, explain the prevention of rusting, and perform crystallisation.',
  },
  {
    grade: '7',
    subject: 'Science',
    chapter: 'Chapter 7: Weather, Climate and Adaptations of Animals to Climate',
    topic: 'Ecology',
    concept: 'Weather vs Climate, Polar/Tropical adaptations',
    learning_objective: 'Understand factors determining weather and explain how animals in polar regions and tropical rainforests adapt.',
  },
  {
    grade: '7',
    subject: 'Science',
    chapter: 'Chapter 8: Winds, Storms and Cyclones',
    topic: 'Meteorology and Earth Science',
    concept: 'Air pressure, Thunderstorms, Cyclones formation',
    learning_objective: 'Demonstrate that air exerts pressure, explain wind currents due to uneven heating, and describe cyclone formation.',
  },
  {
    grade: '7',
    subject: 'Science',
    chapter: 'Chapter 9: Soil',
    topic: 'Soil Science',
    concept: 'Soil Profile, Horizons, Soil types, Percolation rate',
    learning_objective: 'Sketch and label a soil profile, compare sandy, loamy, and clayey soils, and calculate water percolation rate.',
  },
  {
    grade: '7',
    subject: 'Science',
    chapter: 'Chapter 10: Respiration in Organisms',
    topic: 'Biological Respiration',
    concept: 'Aerobic vs Anaerobic Respiration, human breathing mechanism',
    learning_objective: 'Differentiate aerobic from anaerobic respiration, explain inhalation and exhalation, and trace respiration in fish/insects.',
  },
  {
    grade: '7',
    subject: 'Science',
    chapter: 'Chapter 11: Transportation in Animals and Plants',
    topic: 'Physiology',
    concept: 'Circulatory System, Excretory System, Xylem and Phloem',
    learning_objective: 'Explain the function of heart and blood vessels, describe the human urinary system, and explain water/food transport in plants.',
  },
  {
    grade: '7',
    subject: 'Science',
    chapter: 'Chapter 12: Reproduction in Plants',
    topic: 'Plant Reproduction',
    concept: 'Vegetative propagation, Pollination (Self/Cross), Fertilisation',
    learning_objective: 'Distinguish asexual and sexual reproduction, explain vegetative propagation (stem cuttings, budding), and detail seed dispersal.',
  },
  {
    grade: '7',
    subject: 'Science',
    chapter: 'Chapter 13: Motion and Time',
    topic: 'Mechanics and Time measurement',
    concept: 'Speed calculation, Simple Pendulum, Distance-Time graphs',
    learning_objective: 'Measure speed, define time period of a simple pendulum, and draw and interpret distance-time graphs.',
  },
  {
    grade: '7',
    subject: 'Science',
    chapter: 'Chapter 14: Electric Current and its Effects',
    topic: 'Electromagnetism introduction',
    concept: 'Heating effect (fuses), Magnetic effect (Electromagnets)',
    learning_objective: 'Understand electric fuses, build an electromagnet, and explain the working of an electric bell.',
  },
  {
    grade: '7',
    subject: 'Science',
    chapter: 'Chapter 15: Light',
    topic: 'Optics and Images',
    concept: 'Image formation in Plane, Concave, and Convex mirrors/lenses',
    learning_objective: 'Distinguish real and virtual images, describe image characteristics formed by spherical mirrors and lenses, and explain rainbow colors.',
  },

  // === GRADE 8 MATHEMATICS ===
  {
    grade: '8',
    subject: 'Mathematics',
    chapter: 'Chapter 1: Rational Numbers',
    topic: 'Number Properties',
    concept: 'Rational Numbers properties, Density property',
    learning_objective: 'Understand closure, commutative, associative, identity, and distributive properties, and find rational numbers between any two.',
  },
  {
    grade: '8',
    subject: 'Mathematics',
    chapter: 'Chapter 2: Linear Equations in One Variable',
    topic: 'Linear Equations solving',
    concept: 'Solving equations with variables on both sides, word problems',
    learning_objective: 'Solve linear equations in one variable and apply them to solve age, number, and perimeter word problems.',
  },
  {
    grade: '8',
    subject: 'Mathematics',
    chapter: 'Chapter 3: Understanding Quadrilaterals',
    topic: 'Geometry of Polygons',
    concept: 'Angle Sum Property, Parallelogram, Rhombus, Trapezium',
    learning_objective: 'Calculate sum of interior/exterior angles of polygons, and prove and apply properties of special quadrilaterals.',
  },
  {
    grade: '8',
    subject: 'Mathematics',
    chapter: 'Chapter 4: Practical Geometry',
    topic: 'Construction',
    concept: 'Constructing Quadrilaterals with given sides/angles',
    learning_objective: 'Construct quadrilaterals when various combinations of sides, diagonals, and adjacent angles are specified.',
  },
  {
    grade: '8',
    subject: 'Mathematics',
    chapter: 'Chapter 5: Data Handling',
    topic: 'Statistics and Graphs',
    concept: 'Grouped frequency distribution, Histograms, Pie charts',
    learning_objective: 'Organize data using intervals, construct and read histograms and pie charts, and calculate experimental probability.',
  },
  {
    grade: '8',
    subject: 'Mathematics',
    chapter: 'Chapter 6: Squares and Square Roots',
    topic: 'Square Roots',
    concept: 'Properties of Squares, Division/Prime Factorisation methods',
    learning_objective: 'Find squares of numbers, understand Pythagorean triplets, and compute square roots using prime factorisation and long division.',
  },
  {
    grade: '8',
    subject: 'Mathematics',
    chapter: 'Chapter 7: Cubes and Cube Roots',
    topic: 'Cube Roots',
    concept: 'Properties of Cubes, estimation and factorisation methods',
    learning_objective: 'Identify perfect cubes, find cubes of numbers, and calculate cube roots using prime factorisation.',
  },
  {
    grade: '8',
    subject: 'Mathematics',
    chapter: 'Chapter 8: Comparing Quantities',
    topic: 'Commercial Math',
    concept: 'Sales tax/GST, Compound Interest formula',
    learning_objective: 'Calculate discount, markup, sales tax, and compute compound interest annually or half-yearly using the formula.',
  },
  {
    grade: '8',
    subject: 'Mathematics',
    chapter: 'Chapter 9: Algebraic Expressions and Identities',
    topic: 'Algebraic Identities',
    concept: 'Standard Identities (a+b)^2, (a-b)^2, (a^2 - b^2)',
    learning_objective: 'Multiply polynomials (monomials, binomials), and apply algebraic identities to solve numerical computations.',
  },
  {
    grade: '8',
    subject: 'Mathematics',
    chapter: 'Chapter 11: Mensuration',
    topic: 'Geometry and Areas',
    concept: 'Area of Trapezium, Surface Area/Volume of Cubes, Cylinders',
    learning_objective: 'Calculate the total surface area and volume of cubes, cuboids, and cylinders.',
  },
  {
    grade: '8',
    subject: 'Mathematics',
    chapter: 'Chapter 12: Exponents and Powers',
    topic: 'Negative Exponents',
    concept: 'Laws of Exponents for negative powers',
    learning_objective: 'Apply laws of exponents to simplify expressions with negative integer exponents.',
  },
  {
    grade: '8',
    subject: 'Mathematics',
    chapter: 'Chapter 13: Direct and Inverse Proportions',
    topic: 'Proportion',
    concept: 'Direct and Inverse variations',
    learning_objective: 'Identify direct and inverse relationships, formulate equations, and solve direct/inverse variation word problems.',
  },
  {
    grade: '8',
    subject: 'Mathematics',
    chapter: 'Chapter 14: Factorisation',
    topic: 'Factorisation methods',
    concept: 'Common Factors, Regrouping, Identity division',
    learning_objective: 'Factorise algebraic expressions by taking out common factors, regrouping, using identities, and dividing polynomials.',
  },

  // === GRADE 8 SCIENCE ===
  {
    grade: '8',
    subject: 'Science',
    chapter: 'Chapter 1: Crop Production and Management',
    topic: 'Agricultural Sciences',
    concept: 'Sowing, Irrigation, Fertilizers vs Manures, Harvesting, Storage',
    learning_objective: 'Identify agricultural steps, list modern/traditional irrigation methods, differentiate fertilizers and manures, and explain storage.',
  },
  {
    grade: '8',
    subject: 'Science',
    chapter: 'Chapter 2: Microorganisms: Friend and Foe',
    topic: 'Microbiology',
    concept: 'Pathogens, Vaccines, Nitrogen Fixation (Rhizobium)',
    learning_objective: 'Classify microbes, explain how vaccines provide immunity, discuss food preservation, and explain the nitrogen cycle.',
  },
  {
    grade: '8',
    subject: 'Science',
    chapter: 'Chapter 3: Synthetic Fibres and Plastics',
    topic: 'Polymer Chemistry',
    concept: 'Polyesters, Thermoplastics vs Thermosetting, Environment impact',
    learning_objective: 'Distinguish characteristics of nylon, acrylic, and rayon, compare thermoplastics and thermosetting plastics, and outline the 4R principle.',
  },
  {
    grade: '8',
    subject: 'Science',
    chapter: 'Chapter 4: Materials: Metals and Non-Metals',
    topic: 'Inorganic Chemistry',
    concept: 'Malleability, Ductility, Reaction with Acid/Water, Displacement',
    learning_objective: 'Differentiate metals and non-metals physically and chemically, and explain displacement reactions.',
  },
  {
    grade: '8',
    subject: 'Science',
    chapter: 'Chapter 5: Coal and Petroleum',
    topic: 'Fossil Fuels',
    concept: 'Destructive distillation of coal, Petroleum refining',
    learning_objective: 'Describe formation of fossil fuels, list products of coal (coke, coal tar), and explain fractional distillation of petroleum.',
  },
  {
    grade: '8',
    subject: 'Science',
    chapter: 'Chapter 6: Combustion and Flame',
    topic: 'Thermal Chemistry',
    concept: 'Ignition temperature, Inflammable substances, Flame zones',
    learning_objective: 'Explain conditions required for combustion, describe working of fire extinguishers, and draw zones of a candle flame.',
  },
  {
    grade: '8',
    subject: 'Science',
    chapter: 'Chapter 7: Conservation of Plants and Animals',
    topic: 'Biodiversity',
    concept: 'Biosphere Reserves, Endemic Species, Red Data Book',
    learning_objective: 'Explain the impact of deforestation, define wildlife sanctuaries and national parks, and explain reforestation.',
  },
  {
    grade: '8',
    subject: 'Science',
    chapter: 'Chapter 8: Cell — Structure and Functions',
    topic: 'Cell Biology',
    concept: 'Organelles (Mitochondria, Plastids), Plant vs Animal Cells',
    learning_objective: 'State cell theory, describe functions of nucleus, cytoplasm, and cell membrane, and compare plant and animal cells.',
  },
  {
    grade: '8',
    subject: 'Science',
    chapter: 'Chapter 9: Reproduction in Animals',
    topic: 'Developmental Biology',
    concept: 'Internal/External Fertilisation, Metamorphosis, Asexual (Cloning)',
    learning_objective: 'Describe human male/female reproductive systems, detail IVF, explain metamorphosis in frogs/butterflies, and explain budding/fission.',
  },
  {
    grade: '8',
    subject: 'Science',
    chapter: 'Chapter 10: Reaching the Age of Adolescence',
    topic: 'Endocrinology',
    concept: 'Hormones (Thyroxine, Insulin, Adrenaline), Sex Determination',
    learning_objective: 'Describe physical changes during puberty, list endocrine glands and their hormones, and explain chromosomal sex determination.',
  },
  {
    grade: '8',
    subject: 'Science',
    chapter: 'Chapter 11: Force and Pressure',
    topic: 'Physics basics',
    concept: 'Contact/Non-contact forces, Pressure formula, Liquid pressure',
    learning_objective: 'Define force, distinguish contact and non-contact forces, calculate pressure (F/A), and explain atmospheric pressure.',
  },
  {
    grade: '8',
    subject: 'Science',
    chapter: 'Chapter 12: Friction',
    topic: 'Mechanics',
    concept: 'Static, Sliding, Rolling friction, Fluid friction (Drag)',
    learning_objective: 'Explain factors affecting friction, compare sliding and rolling friction, and describe methods to increase or reduce friction.',
  },
  {
    grade: '8',
    subject: 'Science',
    chapter: 'Chapter 13: Sound',
    topic: 'Acoustics',
    concept: 'Amplitude, Frequency, Pitch, Loudness, human larynx',
    learning_objective: 'Explain how sound is produced by vibration, define frequency and amplitude, and discuss noise pollution and its control.',
  },
  {
    grade: '8',
    subject: 'Science',
    chapter: 'Chapter 14: Chemical Effects of Electric Current',
    topic: 'Electrochemistry',
    concept: 'Electrolysis of water, Electroplating process',
    learning_objective: 'Test electrical conductivity of liquids, describe chemical effects of current, and explain the mechanism of electroplating.',
  },
  {
    grade: '8',
    subject: 'Science',
    chapter: 'Chapter 15: Some Natural Phenomena',
    topic: 'Earth Sciences',
    concept: 'Static charges, Lightning conductor, Earthquakes (Seismograph)',
    learning_objective: 'Explain charging by rubbing, describe lightning formation and protection, and explain seismograph recording of earthquakes.',
  },

  // === GRADE 9 MATHEMATICS ===
  {
    grade: '9',
    subject: 'Mathematics',
    chapter: 'Chapter 1: Number Systems',
    topic: 'Real Numbers',
    concept: 'Irrational Numbers, Rationalisation of Denominator, Laws of Real Exponents',
    learning_objective: 'Identify irrational numbers, represent real numbers on a number line, rationalize denominators, and apply laws of exponents to real numbers.',
  },
  {
    grade: '9',
    subject: 'Mathematics',
    chapter: 'Chapter 2: Polynomials',
    topic: 'Polynomial Algebra',
    concept: 'Remainder Theorem, Factor Theorem, Algebraic Identities',
    learning_objective: 'Find zeroes of polynomials, apply remainder and factor theorems, factorise quadratic/cubic polynomials, and apply standard identities.',
  },
  {
    grade: '9',
    subject: 'Mathematics',
    chapter: 'Chapter 3: Coordinate Geometry',
    topic: 'Cartesian Coordinate System',
    concept: 'Axes, Quadrants, Plotting Points',
    learning_objective: 'Understand cartesian coordinate system, identify quadrants, and plot coordinates on a graph.',
  },
  {
    grade: '9',
    subject: 'Mathematics',
    chapter: 'Chapter 4: Linear Equations in Two Variables',
    topic: 'Linear Systems',
    concept: 'Solution of Linear Equations, graphing ax + by + c = 0',
    learning_objective: 'Find general solutions of equations in two variables and plot their linear graphs.',
  },
  {
    grade: '9',
    subject: 'Mathematics',
    chapter: 'Chapter 5: Introduction to Euclid\'s Geometry',
    topic: 'Geometrical Foundations',
    concept: 'Axioms and Postulates, equivalent versions of Euclid\'s 5th Postulate',
    learning_objective: 'Distinguish between axioms, postulates, and theorems, and understand the history of Euclidean geometry.',
  },
  {
    grade: '9',
    subject: 'Mathematics',
    chapter: 'Chapter 6: Lines and Angles',
    topic: 'Geometry of Intersections',
    concept: 'Parallel lines and Transversal properties, Angle Sum of Triangle',
    learning_objective: 'Prove vertically opposite angles are equal, prove parallel lines cut by a transversal properties, and prove triangle angle sum is 180 degrees.',
  },
  {
    grade: '9',
    subject: 'Mathematics',
    chapter: 'Chapter 7: Triangles',
    topic: 'Triangle Congruence',
    concept: 'SAS, ASA, SSS, RHS congruence, Triangle inequalities',
    learning_objective: 'Prove congruence of triangles using various criteria, and apply inequalities in triangles (angle-side relationship).',
  },
  {
    grade: '9',
    subject: 'Mathematics',
    chapter: 'Chapter 8: Quadrilaterals',
    topic: 'Polygon Properties',
    concept: 'Parallelogram properties, Mid-point theorem',
    learning_objective: 'Prove properties of a parallelogram and prove and apply the mid-point theorem.',
  },
  {
    grade: '9',
    subject: 'Mathematics',
    chapter: 'Chapter 10: Circles',
    topic: 'Circle Geometry',
    concept: 'Equal chords properties, Angle subtended by arc, Cyclic Quadrilateral',
    learning_objective: 'Prove equal chords subtend equal angles at centre, explain angles in same segment are equal, and prove cyclic quadrilateral angle properties.',
  },
  {
    grade: '9',
    subject: 'Mathematics',
    chapter: 'Chapter 12: Heron\'s Formula',
    topic: 'Heron\'s Formula applications',
    concept: 'Area of Triangles, application to quadrilateral areas',
    learning_objective: 'Calculate the area of triangles using Heron\'s formula and apply to find areas of quadrilaterals by partitioning.',
  },
  {
    grade: '9',
    subject: 'Mathematics',
    chapter: 'Chapter 13: Surface Areas and Volumes',
    topic: 'Three Dimensional Mensuration',
    concept: 'Surface area and volume of Cylinder, Cone, Sphere',
    learning_objective: 'Compute curved, total surface areas and volumes of right circular cylinders, cones, and spheres.',
  },
  {
    grade: '9',
    subject: 'Mathematics',
    chapter: 'Chapter 14: Statistics',
    topic: 'Statistical Graphs',
    concept: 'Bar graphs, Histograms with varying base, Frequency polygons',
    learning_objective: 'Construct and analyze histograms with varying width and draw frequency polygons to represent data.',
  },

  // === GRADE 9 SCIENCE ===
  {
    grade: '9',
    subject: 'Science',
    chapter: 'Chapter 1: Matter in Our Surroundings',
    topic: 'Physical States of Matter',
    concept: 'Sublimation, Latent Heat of Fusion/Vaporisation, Evaporation factors',
    learning_objective: 'Explain the effect of temperature and pressure on states of matter, define latent heat, and analyze cooling by evaporation.',
  },
  {
    grade: '9',
    subject: 'Science',
    chapter: 'Chapter 2: Is Matter Around Us Pure?',
    topic: 'Solutions and Mixtures',
    concept: 'Colloids, Suspensions, Chromatography, Distillation, Chemical vs Physical changes',
    learning_objective: 'Compare true solutions, suspensions, and colloids, select separation techniques for mixtures, and classify changes.',
  },
  {
    grade: '9',
    subject: 'Science',
    chapter: 'Chapter 3: Atoms and Molecules',
    topic: 'Chemical Bonding and Mole Concept',
    concept: 'Law of Conservation of Mass, Constant Proportions, Formula writing, Moles',
    learning_objective: 'Write chemical formulas using valency, state chemical laws, and convert mass to moles and number of particles.',
  },
  {
    grade: '9',
    subject: 'Science',
    chapter: 'Chapter 4: Structure of the Atom',
    topic: 'Atomic Physics',
    concept: 'Rutherford Alpha scattering, Bohr model, Valence electrons, Isotopes/Isobars',
    learning_objective: 'Compare atomic models of Thomson, Rutherford, and Bohr, determine electron configuration, and explain uses of isotopes.',
  },
  {
    grade: '9',
    subject: 'Science',
    chapter: 'Chapter 5: The Fundamental Unit of Life',
    topic: 'Cellular Structures',
    concept: 'Osmosis, Plasma membrane, Mitochondria, Plastids, Endoplasmic Reticulum',
    learning_objective: 'Explain plant/animal cell structural components, describe passive/active transport, and outline organelle functions.',
  },
  {
    grade: '9',
    subject: 'Science',
    chapter: 'Chapter 6: Tissues',
    topic: 'Histology',
    concept: 'Meristematic/Permanent Plant tissue, Muscle/Nerve/Connective Animal tissue',
    learning_objective: 'Identify types of plant tissues (xylem, phloem) and animal tissues (epithelium, neuron, bone) and relate structure to function.',
  },
  {
    grade: '9',
    subject: 'Science',
    chapter: 'Chapter 8: Motion',
    topic: 'Kinematics',
    concept: 'Velocity-Time graphs, derivation of Equations of Motion, Uniform Circular Motion',
    learning_objective: 'Differentiate speed/velocity and distance/displacement, interpret kinematics graphs, and derive equations of motion.',
  },
  {
    grade: '9',
    subject: 'Science',
    chapter: 'Chapter 9: Force and Laws of Motion',
    topic: 'Dynamics',
    concept: 'Inertia, Newton\'s Three Laws, Conservation of Momentum',
    learning_objective: 'Apply Newton\'s laws of motion to real-world scenarios and solve conservation of momentum equations.',
  },
  {
    grade: '9',
    subject: 'Science',
    chapter: 'Chapter 10: Gravitation',
    topic: 'Gravitational Fields',
    concept: 'Universal Law of Gravitation, Free fall (g), Acceleration due to Gravity, Archimedes Principle',
    learning_objective: 'State universal gravitation law, solve free fall problems, calculate buoyancy, and explain Archimedes principle.',
  },
  {
    grade: '9',
    subject: 'Science',
    chapter: 'Chapter 11: Work and Energy',
    topic: 'Mechanics and Energy',
    concept: 'Work definition, Kinetic Energy, Potential Energy, Conservation of Energy',
    learning_objective: 'Calculate work done, derive Kinetic and Potential Energy equations, and verify the law of conservation of energy.',
  },
  {
    grade: '9',
    subject: 'Science',
    chapter: 'Chapter 12: Sound',
    topic: 'Wave Physics',
    concept: 'Compression/Rarefaction waves, Speed of sound, Echo, Ultrasound, Human Ear',
    learning_objective: 'Explain wave nature of sound, calculate frequency/wavelength/speed, explain sonar/ultrasound, and describe the ear.',
  },
  {
    grade: '9',
    subject: 'Science',
    chapter: 'Chapter 13: Why Do We Fall Ill?',
    topic: 'Immunology and Pathology',
    concept: 'Acute vs Chronic, Infectious vs Non-infectious, Antibiotic mechanism, Immunisation',
    learning_objective: 'Distinguish disease types, list infectious agents, explain principles of treatment, and discuss immunisation.',
  },

  // === GRADE 10 MATHEMATICS ===
  {
    grade: '10',
    subject: 'Mathematics',
    chapter: 'Chapter 1: Real Numbers',
    topic: 'Number Theory',
    concept: 'Fundamental Theorem of Arithmetic, Irrationality of root 2/root 3/root 5',
    learning_objective: 'Apply the Fundamental Theorem of Arithmetic to find HCF/LCM, and prove the irrationality of square roots of prime numbers.',
  },
  {
    grade: '10',
    subject: 'Mathematics',
    chapter: 'Chapter 2: Polynomials',
    topic: 'Advanced Polynomials',
    concept: 'Geometrical Zeroes, relationship between Zeroes and Coefficients',
    learning_objective: 'Interpret zeroes geometrically from graphs, and establish relationships between zeroes and coefficients of quadratic polynomials.',
  },
  {
    grade: '10',
    subject: 'Mathematics',
    chapter: 'Chapter 3: Pair of Linear Equations in Two Variables',
    topic: 'Systems of Equations',
    concept: 'Substitution, Elimination, Consistency conditions',
    learning_objective: 'Solve pairs of linear equations graphically and algebraically (substitution, elimination), and determine consistency conditions.',
  },
  {
    grade: '10',
    subject: 'Mathematics',
    chapter: 'Chapter 4: Quadratic Equations',
    topic: 'Quadratic Functions',
    concept: 'Quadratic Formula, Discriminant, Nature of Roots',
    learning_objective: 'Solve quadratic equations by factorisation and quadratic formula, and determine nature of roots using the discriminant.',
  },
  {
    grade: '10',
    subject: 'Mathematics',
    chapter: 'Chapter 5: Arithmetic Progressions',
    topic: 'Progressions and Sequences',
    concept: 'nth Term of AP, Sum of first n terms of AP',
    learning_objective: 'Derive formula for the nth term and the sum of first n terms of an AP, and solve real-life application problems.',
  },
  {
    grade: '10',
    subject: 'Mathematics',
    chapter: 'Chapter 6: Triangles',
    topic: 'Similarity in Geometry',
    concept: 'Basic Proportionality Theorem, similarity criteria (AAA, SAS, SSS)',
    learning_objective: 'Prove and apply the Basic Proportionality Theorem (Thales theorem) and similarity criteria to solve geometric proofs.',
  },
  {
    grade: '10',
    subject: 'Mathematics',
    chapter: 'Chapter 7: Coordinate Geometry',
    topic: 'Coordinate Geometry applications',
    concept: 'Distance Formula, Section Formula, Area of Triangle coordinates',
    learning_objective: 'Apply distance and section formulas (internal division) and calculate the area of triangles given coordinates.',
  },
  {
    grade: '10',
    subject: 'Mathematics',
    chapter: 'Chapter 8: Introduction to Trigonometry',
    topic: 'Trigonometric Functions',
    concept: 'Trigonometric Ratios, specific angles, Complementary angle ratios, Identities',
    learning_objective: 'Define trigonometric ratios, evaluate specific angles (0, 30, 45, 60, 90), and prove trigonometric identities.',
  },
  {
    grade: '10',
    subject: 'Mathematics',
    chapter: 'Chapter 9: Some Applications of Trigonometry',
    topic: 'Heights and Distances',
    concept: 'Angle of Elevation, Angle of Depression',
    learning_objective: 'Solve multi-step heights and distances problems involving angle of elevation and depression.',
  },
  {
    grade: '10',
    subject: 'Mathematics',
    chapter: 'Chapter 10: Circles',
    topic: 'Circle Geometry Tangents',
    concept: 'Tangent properties, Tangents from external point',
    learning_objective: 'Prove tangent is perpendicular to radius at point of contact, and prove length of tangents from external point are equal.',
  },
  {
    grade: '10',
    subject: 'Mathematics',
    chapter: 'Chapter 12: Areas Related to Circles',
    topic: 'Circular Mensuration',
    concept: 'Area of Sector and Segment of Circle',
    learning_objective: 'Calculate areas of sectors and segments of circles (with central angles of 60, 90, 120 degrees).',
  },
  {
    grade: '10',
    subject: 'Mathematics',
    chapter: 'Chapter 13: Surface Areas and Volumes',
    topic: 'Three Dimensional Geometry',
    concept: 'Surface area/volume of combination of solids, Frustum of Cone',
    learning_objective: 'Find surface area and volume of combined solids (cubes, cylinders, spheres, cones) and solve frustum problems.',
  },
  {
    grade: '10',
    subject: 'Mathematics',
    chapter: 'Chapter 14: Statistics',
    topic: 'Advanced Statistics',
    concept: 'Mean (Direct, Assumed Mean methods), Median, Mode of grouped data, Ogives',
    learning_objective: 'Compute mean, median, and mode for grouped frequency distributions, and construct cumulative frequency graphs (ogives).',
  },

  // === GRADE 10 SCIENCE ===
  {
    grade: '10',
    subject: 'Science',
    chapter: 'Chapter 1: Chemical Reactions and Equations',
    topic: 'Chemical Chemistry',
    concept: 'Balancing Equations, Decomposition, Redox, Rancidity/Corrosion',
    learning_objective: 'Balance chemical equations, identify reaction types (combination, decomposition, displacement, double displacement, oxidation-reduction), and explain corrosion.',
  },
  {
    grade: '10',
    subject: 'Science',
    chapter: 'Chapter 2: Acids, Bases and Salts',
    topic: 'Acid Base Salts',
    concept: 'pH Scale importance, NaOH, Bleaching powder, Baking/Washing Soda, POP',
    learning_objective: 'Understand chemical properties of acids/bases, explain pH importance in daily life, and describe preparation and uses of industrial salts.',
  },
  {
    grade: '10',
    subject: 'Science',
    chapter: 'Chapter 3: Metals and Non-Metals',
    topic: 'Metallurgy and Bonding',
    concept: 'Ionic Compound properties, Basic metallurgical extraction processes, Corrosion prevention',
    learning_objective: 'Describe reactivity series, explain formation of ionic bonds, outline extraction of metals (froth floatation, roasting, calcination), and explain alloying.',
  },
  {
    grade: '10',
    subject: 'Science',
    chapter: 'Chapter 4: Carbon and its Compounds',
    topic: 'Organic Chemistry',
    concept: 'Covalent bonding, Saturated/Unsaturated Hydrocarbons, Homologous Series, Saponification',
    learning_objective: 'Explain versatile nature of carbon, name organic compounds using IUPAC nomenclature, compare soaps/detergents, and explain saponification.',
  },
  {
    grade: '10',
    subject: 'Science',
    chapter: 'Chapter 5: Periodic Classification of Elements',
    topic: 'Inorganic Chemistry and History',
    concept: 'Mendeleev vs Modern Periodic Table, Periodicity trends (Valency, Size)',
    learning_objective: 'Outline historical classification efforts, state Modern Periodic Law, and explain trends in metallic character, atomic radius, and valency.',
  },
  {
    grade: '10',
    subject: 'Science',
    chapter: 'Chapter 6: Life Processes',
    topic: 'Human and Plant Physiology',
    concept: 'Nutrition, Respiration, Double Circulation, Nephron excretion mechanism',
    learning_objective: 'Explain life processes in plants and animals: autotrophic/heterotrophic nutrition, aerobic respiration, double circulation in humans, and nephron filtration.',
  },
  {
    grade: '10',
    subject: 'Science',
    chapter: 'Chapter 7: Control and Coordination',
    topic: 'Neurology and Endocrinology',
    concept: 'Reflex arc, Brain structure, Plant auxins, Animal hormones',
    learning_objective: 'Describe neuron structure, map a reflex arc, label brain regions (forebrain, midbrain, hindbrain), explain phototropism/geotropism, and list animal endocrine glands.',
  },
  {
    grade: '10',
    subject: 'Science',
    chapter: 'Chapter 8: How do Organisms Reproduce?',
    topic: 'Reproductive Biology',
    concept: 'Fission/Budding/Regeneration vegetative, flower parts pollination, human fertilisation, contraception',
    learning_objective: 'Compare asexual reproduction types, explain double fertilisation in angiosperms, detail human male/female reproductive anatomy, and evaluate birth control.',
  },
  {
    grade: '10',
    subject: 'Science',
    chapter: 'Chapter 9: Heredity and Evolution',
    topic: 'Genetics',
    concept: 'Mendel\'s Monohybrid/Dihybrid crosses, Sex determination, Evolution mechanisms',
    learning_objective: 'Describe Mendel\'s laws of inheritance, calculate phenotypic/genotypic ratios, explain human sex determination, and distinguish homologous/analogous organs.',
  },
  {
    grade: '10',
    subject: 'Science',
    chapter: 'Chapter 10: Light — Reflection and Refraction',
    topic: 'Optics and Equations',
    concept: 'Mirror Formula, Refractive Index, Lens Formula, Power of Lens',
    learning_objective: 'Trace ray diagrams for spherical mirrors and lenses, solve mirror and lens formula problems, and calculate power of lens.',
  },
  {
    grade: '10',
    subject: 'Science',
    chapter: 'Chapter 11: Human Eye and Colorful World',
    topic: 'Optics and Vision',
    concept: 'Myopia, Hypermetropia, Dispersion in Prism, Atmospheric Refraction, Tyndall effect',
    learning_objective: 'Draw correction diagrams for myopia and hypermetropia, explain dispersion and scattering of light, and explain atmospheric refraction (twinkling stars).',
  },
  {
    grade: '10',
    subject: 'Science',
    chapter: 'Chapter 12: Electricity',
    topic: 'Electrodynamics',
    concept: 'Ohm\'s Law, Series/Parallel resistance combination, Joule\'s heating law',
    learning_objective: 'Define electric potential and current, prove Ohm\'s law, calculate equivalent resistance, and apply Joule\'s heating formula to appliances.',
  },
  {
    grade: '10',
    subject: 'Science',
    chapter: 'Chapter 13: Magnetic Effects of Electric Current',
    topic: 'Electromagnetism',
    concept: 'Solenoid magnetic field, Fleming\'s Left/Right hand rules, AC vs DC generator',
    learning_objective: 'Trace magnetic field lines of a solenoid, apply Fleming\'s rules, explain electric motor and generator principles, and distinguish domestic circuits.',
  },
];

async function seed() {
  const supabase = getSupabaseAdmin();
  if (!supabase) {
    logger.error('Failed to get Supabase Admin client');
    process.exit(1);
  }

  logger.info('Retrieving CBSE board UUID...');
  const { data: boardRow, error: boardError } = await supabase
    .from('boards')
    .select('id')
    .eq('code', 'CBSE')
    .maybeSingle();

  if (boardError || !boardRow) {
    logger.error('CBSE Board not found. Make sure boards are seeded first.', { error: boardError });
    process.exit(1);
  }

  const boardId = boardRow.id;
  logger.info('CBSE Board ID resolved', { boardId });

  // Delete existing curriculum_hierarchy entries for CBSE board to avoid duplicates
  logger.info('Clearing existing CBSE curriculum entries...');
  const { error: clearError } = await supabase
    .from('curriculum_hierarchy')
    .delete()
    .eq('board_id', boardId);

  if (clearError) {
    logger.error('Failed to clear existing curriculum entries', { error: clearError });
    process.exit(1);
  }

  logger.info(`Inserting ${curriculumData.length} curriculum items for CBSE...`);
  
  const payload = curriculumData.map((item) => ({
    board_id: boardId,
    grade: item.grade,
    subject: item.subject,
    chapter: item.chapter,
    topic: item.topic,
    concept: item.concept,
    learning_objective: item.learning_objective,
  }));

  const { error: insertError } = await supabase
    .from('curriculum_hierarchy')
    .insert(payload);

  if (insertError) {
    logger.error('Failed to seed CBSE curriculum', { error: insertError });
    process.exit(1);
  }

  logger.info('CBSE Curriculum seeded successfully!');
  process.exit(0);
}

seed().catch((err) => {
  logger.error('Unhandled seeding error', { error: err });
  process.exit(1);
});
