import { Router } from 'express';
import courseRoutes from '../course.routes';
import lessonRoutes from '../lesson.routes';
import assignmentRoutes from '../assignment.routes';
import quizRoutes from '../quiz.routes';
import examRoutes from '../exam.routes';
import gradeRoutes from '../grade.routes';
import analyticsRoutes from '../analytics.routes';
import conceptRoutes from '../concept.routes';
import textbookRoutes from '../textbook.routes';
import quizV2Routes from '../quiz-v2.routes';
import assignmentV2Routes from '../assignment-v2.routes';
import examV2Routes from '../exam-v2.routes';
import resultsPushRoutes from '../results-push.routes';
import questionBankRoutes from '../question-bank.routes';
import questionPaperRoutes from '../question-paper.routes';
import testTemplateRoutes from '../test-template.routes';
import testScheduleRoutes from '../test-schedule.routes';
import gamificationRoutes from '../gamification.routes';
import mindmapRoutes from '../mindmap.routes';
import attendanceRoutes from '../attendance.routes';
import schoolAnalyticsRoutes from '../school-analytics.routes';
import codingRoutes from '../coding.routes';
import codingChallengeRoutes from '../coding-challenge.routes';
import prePrimaryRoutes from '../pre-primary.routes';
import nepQuestionsRoutes from '../nep-questions.routes';
import virtualLabsRoutes from '../virtual-labs.routes';
import unifiedTestEngineRoutes from '../unified-test-engine.routes';
import conceptProgressRoutes from '../concept-progress.routes';
import adaptiveRoutes from '../adaptive.routes';
import curriculumRoutes from '../curriculum.routes';
import curriculumPlanRoutes from '../curriculum-plan.routes';
import reportsRoutes from '../reports.routes';
import timetableRoutes from '../timetable.routes';
import parentRoutes from '../parent.routes';
import messageRoutes from '../message.routes';
import notificationRoutes from '../notification.routes';
import noticeRoutes from '../notice.routes';
import ltiRoutes from '../lti.routes';
import reportFeedbackRoutes from '../report-feedback.routes';

const router = Router();

router.use('/courses', courseRoutes);
router.use('/lessons', lessonRoutes);
router.use('/assignments', assignmentRoutes);
router.use('/quizzes', quizRoutes);
router.use('/exams', examRoutes);
router.use('/grades', gradeRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/analytics-v2', analyticsRoutes);
router.use('/whiteboard', conceptRoutes);
router.use('/textbooks', textbookRoutes);
router.use('/quizzes-v2', quizV2Routes);
router.use('/assignments-v2', assignmentV2Routes);
router.use('/exams-v2', examV2Routes);
router.use('/results-push', resultsPushRoutes);
router.use('/question-bank', questionBankRoutes);
router.use('/question-papers', questionPaperRoutes);
router.use('/test-templates', testTemplateRoutes);
router.use('/test-schedule', testScheduleRoutes);
router.use('/gamification', gamificationRoutes);
router.use('/mindmaps', mindmapRoutes);
router.use('/attendance', attendanceRoutes);
router.use('/school-analytics', schoolAnalyticsRoutes);
router.use('/coding', codingRoutes);
router.use('/coding-challenges', codingChallengeRoutes);
router.use('/pre-primary', prePrimaryRoutes);
router.use('/nep-questions', nepQuestionsRoutes);
router.use('/virtual-labs', virtualLabsRoutes);
router.use('/unified-test-engine', unifiedTestEngineRoutes);
router.use('/concept-progress', conceptProgressRoutes);
router.use('/adaptive', adaptiveRoutes);
router.use('/curriculum', curriculumRoutes);
router.use('/', curriculumPlanRoutes);
router.use('/reports', reportsRoutes);
router.use('/timetable', timetableRoutes);
router.use('/parent', parentRoutes);
router.use('/messages', messageRoutes);
router.use('/notifications', notificationRoutes);
router.use('/notices', noticeRoutes);
router.use('/lti', ltiRoutes);
router.use('/report-feedback', reportFeedbackRoutes);

export default router;
